---
- hosts: all
  become: true
  strategy: free
  tasks:
  - name: wget crictl
    shell: 'wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.17.0/crictl-v1.17.0-linux-amd64.tar.gz'
  - name: install crictl
    shell: 'sudo tar zxvf crictl-v1.17.0-linux-amd64.tar.gz -C /usr/local/bin'
    become_user: vagrant
  - name: rm archive
    shell: 'rm crictl-v1.17.0-linux-amd64.*'
  - name: turn off swap
    shell: 'swapoff -a'
