IMAGE_NAME = "bento/ubuntu-20.04"
N = 3

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end
      
    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"#, bridge: "VirtualBox Host-Only Ethernet Adapter"
        master.vm.hostname = "master"
#        master.vm.provision "ansible" do |ansible|
#            ansible.playbook = "setup/master-playbook.yml"
#            ansible.extra_vars = {
#                node_ip: "192.168.50.10",
#            }
#        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"#, bridge: "VirtualBox Host-Only Ethernet Adapter"
            node.vm.hostname = "node-#{i}"
#            node.vm.provision "ansible" do |ansible|
#                ansible.playbook = "setup/node-playbook.yml"
#                ansible.extra_vars = {
#                    node_ip: "192.168.50.#{i + 10}"
#                }
#            end
        end
    end

end
