---
- hosts: all
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - dirmngr

  - name: Add an apt signing key for Clickhouse
    apt_key:
      url: https://repo.yandex.ru/clickhouse/CLICKHOUSE-KEY.GPG
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb https://repo.yandex.ru/clickhouse/deb/stable/ main/
      state: present

  - name: Install Clickhouse and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - clickhouse-server 
      - clickhouse-client
    notify:
      - clickhouse status

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  handlers:
    - name: clickhouse status
      service: name=clickhouse-server state=started
