---
- hosts: all
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - dirmngr

  - name: Add an apt key by id from a keyserver
    ansible.builtin.apt_key:
      keyserver: keyserver.ubuntu.com
      id: 8919F6BD2B48D754

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb https://repo.yandex.ru/clickhouse/deb/stable/ main/
      state: present

  - name: Install Clickhouse and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - clickhouse-server 
      - clickhouse-client
      - clickhouse-common-static
    notify:
      - clickhouse status

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0



  handlers:
    - name: clickhouse status
      service: name=clickhouse-server state=started


    - name: Restart ZooKeeper
      # service:
      #   name: zookeeper.service
      #   state: restarted
      command: /usr/share/zookeeper/bin/zkServer.sh restart

    - name: Restart ClickHouse
      service:
        name: clickhouse-server
        state: restarted